### ISSUE TITLE
Bounce effect when clicking on boundary data

### ISSUE THREAD

**Issue by JGNS** [dhwanish-3/calendar_slider#17]
If you click on the first 1-3 pieces of data, or the last 1-3 pieces of data, the rebound effect should not appear. Is there any way to improve it?

**Comment by JGNS** [comment]
> If you click on the first 1-3 pieces of data, or the last 1-3 pieces of data, the rebound effect should not appear. Is there any way to improve it?

**Comment by JGNS** [comment]
I made some improvements by:

 _goToActualDay(int index) {
    print("_goToActualDay:_dates:${_dates.length},index:$index");
    if (index < _dates.length - 2 && index > 1) _moveToDayIndex(index);
    setState(() {
      _daySelectedIndex = index;
      _selectedDate = _dates[index];
    });
    widget.onDateSelected(_selectedDate);
  }

**Comment by dhwanish-3** [comment]
Please open a pull request with the improvements
